In [ ]:
import json 
# import importlib, final__clean_transform_functions
# importlib.reload(final__clean_transform_functions)

from final__clean_transform_datasets import get_tutor_turn_only_utterances_stepverify, get_all_turn_utterances_stepverify, get_preceding_n_utterance_turns_stepverify

with open("./data/stepverify_labeled_0.9.json", "r", encoding="utf-8") as f:
    stepverify_data = json.load(f)

ModuleNotFoundError: No module named 'final__clean_transform_functions'

In [57]:
stepverify__all_turn__with_speaker_info = get_all_turn_utterances_stepverify(stepverify_data)
stepverify__all_turn__with_speaker_info

                                                  text    label
0    T: tell me your solution </s> S: i think the f...  probing
1    T: hi claire, talk me through your solution </...    focus
2    T: walk me thorugh your solution </s> S: sure....  telling
3    T: hi deandre, talk me through your solution <...  probing
4    T: hi scott talk me through your solution </s>...  probing
..                                                 ...      ...
986  T: hi alejandra. your solution starts very wel...  probing
987  T: hi jordy, i love how you've used algebra to...  telling
988  T: you assumed that the question was asking yo...    focus
989  T: hi mariana, how are you? </s> S: hi, i'm do...  probing
990  T: hi , could you please walk me through your ...    focus

[991 rows x 2 columns]

In [61]:
stepverify__tutor_turn_only = get_tutor_turn_only_utterances_stepverify(stepverify_data)
stepverify__tutor_turn_only

                                                   text    label
0                                 tell me your solution  generic
1              how do you know his friend has 12 tyres?  probing
2              hi claire, talk me through your solution  generic
3     a good start you worked out the ratio was 5 3....    focus
4                         walk me thorugh your solution  telling
...                                                 ...      ...
1977  not quite - what's the total area of the botto...    focus
1978                           hi mariana, how are you?  generic
1979  can you tell me why you did 26 2 in your first...  probing
1980  hi , could you please walk me through your sol...  generic
1981  there seems to be some sort of misunderstandin...    focus

[1982 rows x 2 columns]

In [56]:
stepverify__preceding_1_turn__with_speaker_info = get_preceding_n_utterance_turns_stepverify(stepverify_data, n=1)
stepverify__preceding_1_turn__with_speaker_info

                                                  text    label
0    S: i think the friend has 4 bicycles. since ig...  probing
1    S: i started by looking at the ratio of red ca...    focus
2    S: sure. first, i set up an equation to repres...  telling
3    S: deandre hi, i started by finding out how mu...  probing
4    S: sure. i started by calculating how much mon...  probing
..                                                 ...      ...
986  S: yes, i can. the truck driver needs to trave...  probing
987  S: oh, right! i forgot about the extra 500. le...  telling
988  S: oh, i see now. yes, i can calculate the lef...    focus
989  S: hi, i'm doing well. how can i help you? </s...  probing
990  S: sure. in one day, steve bakes 12 3 4 apple ...    focus

[991 rows x 2 columns]

In [58]:
stepverify__preceding_2_turn__with_speaker_info = get_preceding_n_utterance_turns_stepverify(stepverify_data, n=2)
stepverify__preceding_2_turn__with_speaker_info

                                                  text    label
0    T: tell me your solution </s> S: i think the f...  probing
1    T: hi claire, talk me through your solution </...    focus
2    T: walk me thorugh your solution </s> S: sure....  telling
3    T: hi deandre, talk me through your solution <...  probing
4    T: hi scott talk me through your solution </s>...  probing
..                                                 ...      ...
986  T: hi alejandra. your solution starts very wel...  probing
987  T: hi jordy, i love how you've used algebra to...  telling
988  T: you assumed that the question was asking yo...    focus
989  T: hi mariana, how are you? </s> S: hi, i'm do...  probing
990  T: hi , could you please walk me through your ...    focus

[991 rows x 2 columns]

In [ ]:
stepverify__tutor_turn_only.to_csv("./data/stepverify__tutor_turn_only.csv", index=False)
stepverify__all_turn__with_speaker_info.to_csv("./data/stepverify__all_turns.csv", index=False)
stepverify__preceding_1_turn__with_speaker_info.to_csv("./data/stepverify__preceding_1_turn.csv", index=False)
stepverify__preceding_2_turn__with_speaker_info.to_csv("./data/stepverify__preceding_2_turn.csv", index=False)